/*
 * kernels/gaussian/serial.c
 *
 * Serial Gaussian elimination with back-substitution: solves A x = b for x,
 * given an N x N matrix A and length-N vector b.
 *
 * NO PIVOTING. This is deliberate, not a shortcut: A is generated by
 * common/genmat.h's genmat_diag_dominant(), which is documented there
 * specifically to make naive (no-pivot) elimination numerically stable --
 * strict diagonal dominance (|A[i][i]| > sum of |A[i][j]|, j != i, every
 * row) guarantees every pivot encountered during elimination stays safely
 * away from zero, so there's no risk of dividing by a tiny or zero pivot.
 * Partial pivoting (searching each column for the largest remaining entry
 * and swapping rows) is the standard fix when that guarantee doesn't hold
 * -- it isn't needed here, and skipping it also considerably simplifies
 * the upcoming MPI version (no need to communicate pivot-search results
 * across ranks, only the pivot row's data itself).
 *
 * ALGORITHM, two phases:
 *
 *   1. Forward elimination: for each pivot row k (0..n-2), and each row i
 *      below it, compute factor = A[i][k] / A[k][k], then subtract
 *      (factor * row k) from row i (and the same factor*b[k] from b[i]).
 *      This zeroes out A[i][k] for every i > k, one column at a time,
 *      turning A into upper-triangular form. b is transformed alongside A
 *      so that the *system* A x = b stays equivalent throughout -- same
 *      solution x, just an easier-to-solve shape.
 *
 *   2. Back-substitution: once A is upper-triangular, x[n-1] can be read
 *      off directly (only one unknown left in that row), then x[n-2] is
 *      solvable using x[n-1], and so on up to x[0]. Working from the
 *      bottom row up is what "back" refers to.
 *
 * A CORRECTNESS/PERFORMANCE INSIGHT WORTH KNOWING: this kernel modifies A
 * and b IN PLACE, unlike matmul/matvec which only ever read their inputs.
 * That's normally a red flag for bench.c's warm-up-then-repeat harness --
 * if a kernel mutates its input, calling it twice in a row on the SAME
 * buffers would look like it's solving a different, already-half-solved
 * problem the second time. Here it happens to be safe anyway: once A is
 * upper-triangular, every entry below the diagonal is already exactly
 * zero, so a second elimination pass computes factor = 0/pivot = 0 for
 * every row and subtracts nothing -- it's a genuine fixed point. Back-
 * substitution then recomputes the identical x from the same (unchanged)
 * A and b. So repeated calls execute the same number of loop iterations
 * (the timing stays honest) and produce bit-identical results every time
 * (a good sanity property, not just a lucky accident) -- but this only
 * holds because there's no pivoting to reorder rows differently on a
 * second pass. Worth remembering if pivoting is ever added later.
 */

#include <stdio.h>
#include <stdlib.h>

#include "types.h"
#include "genmat.h"
#include "bench.h"

typedef struct {
    real *A;   /* n x n, modified in place */
    real *b;   /* length n, modified in place */
    real *x;   /* length n, output */
    int n;
} gaussian_arg;

static void forward_eliminate(real *A, real *b, int n)
{
    for (int k = 0; k < n - 1; k++) {
        const real pivot = A[k * n + k];
        for (int i = k + 1; i < n; i++) {
            const real factor = A[i * n + k] / pivot;
            for (int j = k; j < n; j++) {
                A[i * n + j] -= factor * A[k * n + j];
            }
            b[i] -= factor * b[k];
        }
    }
}

static void back_substitute(const real *A, const real *b, real *x, int n)
{
    for (int i = n - 1; i >= 0; i--) {
        real sum = b[i];
        for (int j = i + 1; j < n; j++) {
            sum -= A[i * n + j] * x[j];
        }
        x[i] = sum / A[i * n + i];
    }
}

static void gaussian_kernel(void *arg)
{
    gaussian_arg *a = (gaussian_arg *)arg;
    forward_eliminate(a->A, a->b, a->n);
    back_substitute(a->A, a->b, a->x, a->n);
}

static void usage(const char *prog)
{
    fprintf(stderr, "usage: %s -n <size> [-r <reps>] [-t <threads>]\n", prog);
}

int main(int argc, char **argv)
{
    bench_config cfg;
    if (bench_parse_args(argc, argv, &cfg) != 0) {
        usage(argv[0]);
        return 1;
    }
    (void)cfg.threads; /* unused -- single-core code, same as other *_serial files */

    const int n = cfg.n;

    real *A = malloc((size_t)n * n * sizeof(real));
    real *b = malloc((size_t)n * sizeof(real));
    real *x = malloc((size_t)n * sizeof(real));
    if (!A || !b || !x) {
        fprintf(stderr, "allocation failed for n=%d\n", n);
        free(A); free(b); free(x);
        return 1;
    }

    /* Same seed convention as every other kernel: first input (A) = 42,
     * second input (b) = 43. A must be diag-dominant for no-pivot
     * elimination to be safe -- b has no such requirement, any values
     * work as a right-hand side. */
    genmat_diag_dominant(A, n, 42);
    genmat_random(b, n, 1, 43);

    gaussian_arg arg = { A, b, x, n };

    double time_min, time_med;
    bench_run(gaussian_kernel, &arg, &cfg, &time_min, &time_med);

    real sum_x = 0.0;
    for (int i = 0; i < n; i++) sum_x += x[i];
    fprintf(stderr, "sum(x)=%.7e x[0]=%.7e x[n-1]=%.7e\n",
            (double)sum_x, (double)x[0], (double)x[n - 1]);

    /* Standard leading-order flop count for Gaussian elimination is
     * (2/3)*n^3 -- the O(n^2) back-substitution term is dropped as
     * negligible for any n large enough to be worth benchmarking, same
     * "good enough for roofline order-of-magnitude" spirit as every
     * other kernel's estimate here. */
    double flops = (2.0 / 3.0) * (double)n * (double)n * (double)n;
    double gflops = flops / time_min / 1e9;

    /* Working-set estimate, same caveat as every other kernel's CSV:
     * read A (n^2), read b (n), write x (n) -- ignores the enormous
     * amount of re-reading/re-writing A actually does during elimination
     * itself. Revisited properly at Phase 5. */
    double gbytes_s = ((double)n * n + 2.0 * n) * sizeof(real) / time_min / 1e9;

    bench_report_csv(stdout, "gaussian", "serial", n, 1,
                      time_min, time_med, gflops, gbytes_s);

    free(A);
    free(b);
    free(x);
    return 0;
}
